#padata:
#  build: data/.
#  volumes:
#    - padata:/data
#    - pasrc:/src
#    - painit:/init
popit:
  build: popit/.
  volumes:
    - popitdata:/data
    - popitsrc:/src
  ports:
    - "8000:8000"
billit:
  build: billit/.
  volumes:
    - billitdata:/data
    - billitsrc:/src
  ports:
    - "8002:8002"
##legislative:
#  build: legislative/.
#  #volumes: 
#    #- $PA_BILLIT_REP:$PA_BILLIT_GEM 
#    #- $PA_POPIT_REP:$PA_POPIT_GEM
#  volumes_from:
#    - padata
#  ports:
#    - "5000:5000"
#
