#!/bin/bash

#Init script for legislative and related platforms
# Completar el camino absolito a legislative
LEGISLATIVE_HOME=

start() {
    . $LEGISLATIVE_HOME/local-pa-config.sh

    sh $LEGISLATIVE_HOME/popit/stop-server.sh
    sleep 1
    sh $LEGISLATIVE_HOME/billit/stop-server.sh

    echo "Starting Popit container"
    sh $LEGISLATIVE_HOME/popit/server-run.sh
    sleep 1
    # Inicio watchdog debido a la muerte repentina de popit y la falta de soporte
    nohup sh $LEGISLATIVE_HOME/popit_watchdog.sh & 
    echo "Starting Bill-it container"
    sh $LEGISLATIVE_HOME/billit/server-run.sh
    sleep 1
    echo "Starting Legislative container"
    sh $LEGISLATIVE_HOME/legislative/server-run.sh
    sleep 1
    # Watchdog para legislative
    nohup sh $LEGISLATIVE_HOME/leglsative_watchdog.sh &
}

stop() {
    echo "stopping legislative"
    . $LEGISLATIVE_HOME/local-pa-config.sh
    # Mato al watchdog para que no vuelva a iniciar sinquerer
    killall popit_watchdog.sh
    sleep 1
    sh $LEGISLATIVE_HOME/popit/stop-server.sh
    sleep 1
    sh $LEGISLATIVE_HOME/billit/stop-server.sh
    # Mato al watchdog para que no vuelva a iniciar sinquerer
    killall legislative_watchdog.sh
    sleep 1
    sh $LEGISLATIVE_HOME/legislative/stop-server.sh
    sleep 1
}

status() {
    echo "status"
    
}

case "$1" in
    start)
	start
    ;;
    stop)
	stop
    ;;
    restart)
	stop
	sleep 1
	start
	;;
    status)
#just show docker ps
	docker ps
	;;
    *)
	#log_success_msg "Usage: /etc/init.d/legislative {start|stop|restart|status}"
	echo "Usage: /etc/init.d/legislative {start|stop|restart|status}"
exit 1
esac

